// components/event-agenda-section.tsx
"use client"

import { Clock, Music, MapPin, Calendar } from "lucide-react"
import Image from "next/image"

interface Artist {
  id: string
  name: string
  stage: string
  startTime: string
  endTime: string
  genre: string
  image: string
  description?: string
}

interface EventAgenda {
  id: string
  title: string
  date: string
  venue: string
  artists: Artist[]
}

const upcomingEvent: EventAgenda = {
  id: "hakborrel-2024",
  title: "HAKBORREL 2024 - UNDERGROUND RAVE",
  date: "2024-03-15",
  venue: "Secret Location, Amsterdam",
  artists: [
    {
      id: "dj-1",
      name: "DJ HARDCORE MASTER",
      stage: "Main Stage",
      startTime: "23:00",
      endTime: "01:00",
      genre: "Hardcore Techno",
      image: "/placeholder.svg",
      description: "Legendary hardcore DJ with 15+ years in the underground scene"
    },
    {
      id: "dj-2", 
      name: "BASS DESTROYER",
      stage: "Main Stage",
      startTime: "01:00",
      endTime: "03:00",
      genre: "Raw Hardcore",
      image: "/placeholder.svg",
      description: "Known for earth-shaking basslines and relentless energy"
    },
    {
      id: "dj-3",
      name: "UNDERGROUND LEGEND",
      stage: "Main Stage", 
      startTime: "03:00",
      endTime: "05:00",
      genre: "Industrial Hardcore",
      image: "/placeholder.svg",
      description: "Pioneer of the underground movement, bringing authentic vibes"
    },
    {
      id: "dj-4",
      name: "RAVE WARRIOR",
      stage: "Main Stage",
      startTime: "05:00", 
      endTime: "07:00",
      genre: "Frenchcore",
      image: "/placeholder.svg",
      description: "Closing the night with explosive Frenchcore energy"
    }
  ]
}

export function EventAgendaSection() {
  return (
    <section className="relative py-24 px-6 overflow-hidden">
      {/* Clean, simple background */}
      <div className="absolute inset-0 bg-black" />
      <div className="absolute inset-0 bg-gradient-to-br from-primary/5 via-transparent to-secondary/5" />

      <div className="container mx-auto relative z-10 max-w-6xl">
        {/* Professional header */}
        <div className="text-center mb-16">
          <div className="inline-flex items-center gap-3 mb-6">
            <div className="w-1 h-8 bg-primary"></div>
            <h2 className="text-4xl md:text-6xl font-bold">
              <span className="text-white">EVENT</span>{" "}
              <span className="text-primary">AGENDA</span>
            </h2>
            <div className="w-1 h-8 bg-primary"></div>
          </div>
          <p className="text-gray-300 text-lg max-w-2xl mx-auto leading-relaxed mb-8">
            Check out the lineup and schedule for our upcoming underground gathering.
          </p>
          
          {/* Event info */}
          <div className="bg-black/60 backdrop-blur-sm border border-primary/30 rounded-xl p-6 max-w-2xl mx-auto">
            <h3 className="text-primary text-2xl font-bold mb-4">{upcomingEvent.title}</h3>
            <div className="flex flex-wrap justify-center gap-6 text-sm text-gray-300">
              <div className="flex items-center gap-2">
                <Calendar className="h-4 w-4 text-primary" />
                <span>{new Date(upcomingEvent.date).toLocaleDateString('en-US', { 
                  weekday: 'long', 
                  year: 'numeric', 
                  month: 'long', 
                  day: 'numeric' 
                })}</span>
              </div>
              <div className="flex items-center gap-2">
                <MapPin className="h-4 w-4 text-primary" />
                <span>{upcomingEvent.venue}</span>
              </div>
            </div>
          </div>
        </div>

        {/* Artist lineup */}
        <div className="space-y-6">
          <h3 className="text-2xl font-bold text-center text-white mb-8">ARTIST LINEUP</h3>
          
          {upcomingEvent.artists.map((artist, index) => (
            <div 
              key={artist.id}
              className="bg-black/60 backdrop-blur-sm border border-gray-700/50 rounded-xl p-6 hover:border-primary/50 transition-all duration-300 group"
            >
              <div className="flex items-center gap-6">
                {/* Artist image */}
                <div className="relative w-20 h-20 rounded-lg overflow-hidden flex-shrink-0">
                  <Image
                    src={artist.image}
                    alt={artist.name}
                    fill
                    className="object-cover group-hover:scale-105 transition-transform duration-300"
                  />
                </div>

                {/* Artist info */}
                <div className="flex-1 min-w-0">
                  <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-2">
                    <div>
                      <h4 className="text-xl font-bold text-white mb-1">{artist.name}</h4>
                      <p className="text-primary text-sm font-medium">{artist.genre}</p>
                      {artist.description && (
                        <p className="text-gray-400 text-sm mt-1">{artist.description}</p>
                      )}
                    </div>
                    
                    {/* Time and stage info */}
                    <div className="flex flex-col md:items-end gap-2">
                      <div className="flex items-center gap-4 text-sm">
                        <div className="flex items-center gap-1 text-gray-300">
                          <Clock className="h-4 w-4" />
                          <span>{artist.startTime} - {artist.endTime}</span>
                        </div>
                        <div className="flex items-center gap-1 text-gray-300">
                          <Music className="h-4 w-4" />
                          <span>{artist.stage}</span>
                        </div>
                      </div>
                      
                      {/* Performance slot indicator */}
                      <div className="flex items-center gap-2">
                        <div className="w-2 h-2 bg-primary rounded-full"></div>
                        <span className="text-xs text-gray-400">Slot {index + 1}</span>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>

        {/* Additional info */}
        <div className="mt-12">
          <div className="bg-black/60 backdrop-blur-sm border border-secondary/30 rounded-xl p-8 max-w-4xl mx-auto hover:border-secondary/50 transition-all duration-300">
            <div className="flex items-center justify-center gap-3 mb-8">
              <div className="w-1 h-6 bg-secondary"></div>
              <h4 className="text-secondary text-xl font-bold">EVENT DETAILS</h4>
              <div className="w-1 h-6 bg-secondary"></div>
            </div>
            
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
              <div className="text-center group">
                <div className="bg-primary/10 border border-primary/20 rounded-xl p-6 mb-4 group-hover:bg-primary/20 transition-all duration-300">
                  <div className="text-3xl font-bold text-primary mb-2">22:30</div>
                  <div className="text-gray-300 text-sm font-medium">DOORS OPEN</div>
                </div>
              </div>
              
              <div className="text-center group">
                <div className="bg-secondary/10 border border-secondary/20 rounded-xl p-6 mb-4 group-hover:bg-secondary/20 transition-all duration-300">
                  <div className="text-3xl font-bold text-secondary mb-2">18+</div>
                  <div className="text-gray-300 text-sm font-medium">AGE LIMIT</div>
                </div>
              </div>
              
              <div className="text-center group">
                <div className="bg-primary/10 border border-primary/20 rounded-xl p-6 mb-4 group-hover:bg-primary/20 transition-all duration-300">
                  <div className="text-2xl font-bold text-primary mb-2">UNDERGROUND</div>
                  <div className="text-gray-300 text-sm font-medium">DRESS CODE</div>
                </div>
              </div>
              
              <div className="text-center group">
                <div className="bg-secondary/10 border border-secondary/20 rounded-xl p-6 mb-4 group-hover:bg-secondary/20 transition-all duration-300">
                  <div className="text-2xl font-bold text-secondary mb-2">24H</div>
                  <div className="text-gray-300 text-sm font-medium">LOCATION NOTICE</div>
                </div>
              </div>
            </div>
            
            <div className="mt-8 pt-6 border-t border-gray-700/50">
              <div className="text-center text-gray-400 text-sm">
                <p>Bring your ID, wear your best underground gear, and get ready for an unforgettable night.</p>
                <p className="mt-2">Location details will be sent to your email 24 hours before the event.</p>
              </div>
            </div>
          </div>
          
          <div className="mt-8 text-center">
            <button className="bg-primary hover:bg-primary/90 text-black font-semibold px-8 py-4 rounded-lg transition-all duration-300 hover:scale-105 shadow-lg hover:shadow-xl cursor-pointer">
              GET TICKETS
            </button>
          </div>
        </div>
      </div>
    </section>
  )
}

// app/components/EventAgendaSection.vue
    <template>
  <!-- Event Agenda Section -->
  <section id="agenda" class="relative section-padding overflow-hidden">
    <!-- Agenda-specific background elements -->
    <div 
      class="absolute inset-0 opacity-10"
      style="
        background-image: url('data:image/svg+xml,%3Csvg width=\'60\' height=\'60\' viewBox=\'0 0 60 60\' xmlns=\'http://www.w3.org/2000/svg\'%3E%3Cg fill=\'%23ffffff\' fill-opacity=\'0.02\'%3E%3Ccircle cx=\'10\' cy=\'10\' r=\'1\'/%3E%3Ccircle cx=\'30\' cy=\'10\' r=\'1\'/%3E%3Ccircle cx=\'50\' cy=\'10\' r=\'1\'/%3E%3Ccircle cx=\'10\' cy=\'30\' r=\'1\'/%3E%3Ccircle cx=\'30\' cy=\'30\' r=\'1\'/%3E%3Ccircle cx=\'50\' cy=\'30\' r=\'1\'/%3E%3Ccircle cx=\'10\' cy=\'50\' r=\'1\'/%3E%3Ccircle cx=\'30\' cy=\'50\' r=\'1\'/%3E%3Ccircle cx=\'50\' cy=\'50\' r=\'1\'/%3E%3C/g%3E%3C/svg%3E');
        animation: hexagon-move 15s linear infinite;
      "
    />

    <!-- Subtle side glows -->
    <div class="absolute top-1/2 left-0 w-60 h-60 bg-green-500/12 rounded-full blur-[100px] -translate-y-1/2 animate-smooth-flow" style="animation-duration: 8s;" />
    <div class="absolute top-1/2 right-0 w-60 h-60 bg-purple-500/12 rounded-full blur-[100px] -translate-y-1/2 animate-smooth-flow" style="animation-duration: 10s; animation-delay: 2s;" />
    
    <!-- Subtle floating agenda indicators -->
    <div class="absolute top-1/4 left-1/4 w-4 h-4 bg-green-500/25 rounded-full animate-wave-motion" style="animation-duration: 6s;" />
    <div class="absolute top-1/4 right-1/4 w-4 h-4 bg-purple-500/25 rounded-full animate-wave-motion" style="animation-duration: 7s; animation-delay: 1s;" />
    
    <!-- Subtle floating particles -->
    <div class="absolute top-1/3 left-1/3 w-2 h-2 bg-green-500/15 rounded-full animate-atmospheric-drift" />
    <div class="absolute bottom-1/3 right-1/3 w-2 h-2 bg-purple-500/15 rounded-full animate-atmospheric-drift" style="animation-delay: 3s;" />
    
    <!-- Subtle central accent -->
    <div class="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-80 h-80 bg-gradient-to-r from-green-500/10 to-purple-500/10 rounded-full blur-[120px] animate-subtle-glow" style="animation-duration: 6s;" />

    <div class="container mx-auto px-4 sm:px-6 relative z-10">
      <!-- Professional header -->
      <div class="text-center mb-20">
        <div class="inline-flex items-center gap-4 mb-8">
          <div class="w-1 h-12 bg-gradient-to-b from-green-500 to-green-500/50"></div>
          <h2 class="text-5xl md:text-7xl font-display">
            <span class="text-white">EVENT </span>
            <span class="text-gradient-primary">AGENDA</span>
          </h2>
          <div class="w-1 h-12 bg-gradient-to-b from-green-500 to-green-500/50"></div>
        </div>
        <p class="text-gray-300 text-xl max-w-3xl mx-auto leading-relaxed font-body mb-12">
          Check out the complete lineup and schedule for our upcoming event.
        </p>

        <!-- Event info card -->
        <div class="card-professional p-8 max-w-4xl mx-auto mb-16">
          <div class="grid grid-cols-1 md:grid-cols-3 gap-8">
            <div class="text-center">
              <div class="bg-green-500/20 p-4 rounded-xl border border-green-500/30 w-fit mx-auto mb-4">
                <svg class="h-8 w-8 text-green-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
                </svg>
              </div>
              <h3 class="text-gradient-primary text-xl font-heading mb-2">DATE</h3>
              <p class="text-gray-300 font-body">{{ formatDate(eventInfo.date) }}</p>
            </div>
            <div class="text-center">
              <div class="bg-purple-500/20 p-4 rounded-xl border border-purple-500/30 w-fit mx-auto mb-4">
                <svg class="h-8 w-8 text-purple-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z" />
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 11a3 3 0 11-6 0 3 3 0 016 0z" />
                </svg>
              </div>
              <h3 class="text-gradient-secondary text-xl font-heading mb-2">VENUE</h3>
              <p class="text-gray-300 font-body">{{ eventInfo.venue }}</p>
            </div>
            <div class="text-center">
              <div class="bg-green-500/20 p-4 rounded-xl border border-green-500/30 w-fit mx-auto mb-4">
                <svg class="h-8 w-8 text-green-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
                </svg>
              </div>
              <h3 class="text-gradient-primary text-xl font-heading mb-2">TIMES</h3>
              <p class="text-gray-300 font-body">Doors: {{ eventInfo.doors }} | End: {{ eventInfo.end }}</p>
            </div>
          </div>
        </div>
      </div>

      <!-- Lineup display -->
      <div class="max-w-6xl mx-auto mb-16">
        <div
          v-for="stage in lineupData"
          :key="stage.id"
          class="mb-16"
        >
          <div class="text-center mb-8">
            <h3 :class="[
              'text-3xl font-display mb-2',
              stage.color === 'primary' ? 'text-gradient-primary' : 'text-gradient-secondary'
            ]">
              {{ stage.name }}
            </h3>
            <div :class="[
              'w-24 h-1 mx-auto rounded-full',
              stage.color === 'primary' ? 'bg-green-500' : 'bg-purple-500'
            ]"></div>
          </div>

          <div class="space-y-4">
            <div
              v-for="(event, index) in stage.events"
              :key="index"
              class="bg-black/80 backdrop-blur-sm border border-green-500/30 rounded-2xl p-4 sm:p-6 hover:border-green-500/60 transition-all duration-300 hover:bg-black/90 group"
            >
              <!-- Mobile Layout: Stack vertically -->
              <div class="flex flex-col sm:hidden gap-4">
                <!-- Top Row: Date and Icon with Title -->
                <div class="flex items-center gap-3">
                  <div class="flex flex-col items-center min-w-[50px]">
                    <div class="text-2xl font-bold text-green-500">
                      {{ event.date }}
                    </div>
                    <div class="text-gray-400 text-xs font-body uppercase tracking-wide">
                      {{ event.month }}
                    </div>
                  </div>
                  <div :class="[
                    'w-12 h-12 rounded-xl flex items-center justify-center flex-shrink-0',
                    stage.color === 'primary' 
                      ? 'bg-gradient-to-b from-green-500/30 to-purple-500/30 border border-green-500/30' 
                      : 'bg-gradient-to-b from-purple-500/30 to-green-500/30 border border-purple-500/30'
                  ]">
                    <span class="text-white text-xs font-bold uppercase">
                      {{ event.icon }}
                    </span>
                  </div>
                  <div class="flex-1 min-w-0">
                    <h4 class="text-white text-base font-heading truncate h-6 leading-6">{{ event.artist }}</h4>
                  </div>
                </div>
                
                <!-- Details Section -->
                <div class="pl-1">
                  <p class="text-gray-400 text-sm font-body truncate mb-1">{{ event.location }}</p>
                  <p class="text-green-500 font-body text-sm">{{ event.time }}</p>
                </div>

                <!-- Actions -->
                <div>
                  <button class="border border-gray-400 text-gray-400 hover:border-green-500 hover:text-green-500 px-4 py-2 rounded-full text-sm font-body transition-all duration-300 w-full text-center">
                    Meer info
                  </button>
                </div>
              </div>

              <!-- Desktop Layout: Horizontal -->
              <div class="hidden sm:flex items-center gap-4 md:gap-6">
                <!-- Date Section -->
                <div class="flex flex-col items-center min-w-[80px]">
                  <div class="text-4xl font-bold text-green-500 mb-1">
                    {{ event.date }}
                  </div>
                  <div class="text-gray-400 text-sm font-body uppercase tracking-wide">
                    {{ event.month }}
                  </div>
                </div>

                <!-- Event Icon -->
                <div :class="[
                  'w-16 h-16 rounded-xl flex items-center justify-center flex-shrink-0',
                  stage.color === 'primary' 
                    ? 'bg-gradient-to-b from-green-500/30 to-purple-500/30 border border-green-500/30' 
                    : 'bg-gradient-to-b from-purple-500/30 to-green-500/30 border border-purple-500/30'
                ]">
                  <span class="text-white text-xs font-bold uppercase">
                    {{ event.icon }}
                  </span>
                </div>

                <!-- Event Details -->
                <div class="flex-1 min-w-0">
                  <h4 class="text-white text-xl font-heading mb-2">{{ event.artist }}</h4>
                  <p class="text-gray-400 font-body mb-1 truncate">{{ event.location }}</p>
                  <p class="text-green-500 font-body text-sm">{{ event.time }}</p>
                </div>

                <!-- Actions -->
                <div class="flex flex-col items-end gap-3 flex-shrink-0">
                  <button class="border border-gray-400 text-gray-400 hover:border-green-500 hover:text-green-500 px-4 py-2 rounded-full text-sm font-body transition-all duration-300 whitespace-nowrap">
                    Meer info
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- Professional action button -->
      <div class="text-center mt-20">
        <button class="btn-professional px-12 py-4 text-lg cursor-pointer">
          GET TICKETS NOW
        </button>
      </div>
    </div>
  </section>
</template>

<script setup>

// Sample lineup data - replace with real data
const lineupData = [
  {
    id: "main-stage",
    name: "MAIN STAGE",
    color: "primary",
    events: [
      { 
        date: "20", 
        month: "SEPTEMBER", 
        time: "22:00 - 06:00", 
        artist: "THUNDER STORM", 
        genre: "Hardcore", 
        location: "Industrial Warehouse, Rotterdam",
        status: "confirmed",
        icon: "THUNDER"
      },
      { 
        date: "21", 
        month: "SEPTEMBER", 
        time: "23:00 - 05:00", 
        artist: "BASS DESTROYER", 
        genre: "Hardcore", 
        location: "Industrial Warehouse, Rotterdam",
        status: "confirmed",
        icon: "BASS"
      },
      { 
        date: "22", 
        month: "SEPTEMBER", 
        time: "22:30 - 06:30", 
        artist: "NEON PULSE", 
        genre: "Hardcore", 
        location: "Industrial Warehouse, Rotterdam",
        status: "confirmed",
        icon: "NEON"
      },
    ]
  }
]

const eventInfo = {
  date: "2024-04-20",
  venue: "Industrial Warehouse, Rotterdam",
  doors: "21:00",
  end: "06:00"
}

const formatDate = (dateString) => {
  return new Date(dateString).toLocaleDateString('en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  })
}
</script>
