// components/navigation.tsx
"use client"

import { Search } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import Link from "next/link"
import { useState } from "react"
import { useRouter, usePathname } from "next/navigation"

export function Navigation() {
  const [isMenuOpen, setIsMenuOpen] = useState(false)
  const router = useRouter()
  const pathname = usePathname()

  const scrollToSection = (sectionId: string) => {
    // If we're not on the home page, navigate to home first
    if (pathname !== '/') {
      router.push('/#' + sectionId)
    } else {
      const element = document.getElementById(sectionId)
      if (element) {
        element.scrollIntoView({ behavior: 'smooth' })
      }
    }
    setIsMenuOpen(false)
  }

  const navigateToHome = () => {
    if (pathname !== '/') {
      router.push('/')
    } else {
      scrollToSection('home')
    }
  }

  return (
    <nav className="fixed top-0 left-0 right-0 z-50 bg-black/80 backdrop-blur-sm border-b border-white/10">
      <div className="container mx-auto px-6 py-4">
        <div className="flex items-center justify-between">
          {/* Logo */}
          <button onClick={navigateToHome} className="flex items-center hover:scale-105 transition-transform">
            <div 
              className="w-10 h-10 bg-contain bg-no-repeat bg-center"
              style={{
                backgroundImage: "url('/logo/HakBorrel-LOGOS_white 1.png')"
              }}
            />
            <span className="text-white font-bold text-lg ml-3">HAKBORREL</span>
          </button>

          {/* Desktop Navigation Links */}
          <div className="hidden md:flex items-center gap-6">
            <button onClick={navigateToHome} className="text-white hover:text-primary transition-colors font-medium text-sm tracking-wide hover:scale-105 cursor-pointer">
              HOME
            </button>
            <button onClick={() => scrollToSection('events')} className="text-white hover:text-primary transition-colors font-medium text-sm tracking-wide hover:scale-105 cursor-pointer">
              EVENTS
            </button>
            <button onClick={() => scrollToSection('videos')} className="text-white hover:text-primary transition-colors font-medium text-sm tracking-wide hover:scale-105 cursor-pointer">
              VIDEO'S
            </button>
            <button onClick={() => scrollToSection('community')} className="text-white hover:text-primary transition-colors font-medium text-sm tracking-wide hover:scale-105 cursor-pointer">
              COMMUNITY
            </button>
            <button onClick={() => scrollToSection('story')} className="text-white hover:text-primary transition-colors font-medium text-sm tracking-wide hover:scale-105 cursor-pointer">
              STORY
            </button>
            <button onClick={() => scrollToSection('media')} className="text-white hover:text-primary transition-colors font-medium text-sm tracking-wide hover:scale-105 cursor-pointer">
              MEDIA
            </button>
            <Link href="/tickets" className="text-white hover:text-primary transition-colors font-medium text-sm tracking-wide hover:scale-105 cursor-pointer">
              TICKETS
            </Link>
          </div>

          {/* Mobile Menu Button */}
          <button
            onClick={() => setIsMenuOpen(!isMenuOpen)}
            className="md:hidden text-white hover:text-primary transition-colors"
          >
            <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              {isMenuOpen ? (
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
              ) : (
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 6h16M4 12h16M4 18h16" />
              )}
            </svg>
          </button>

          {/* Desktop Search and Actions */}
          <div className="hidden md:flex items-center gap-3">
            <div className="relative hidden lg:block">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-gray-400" />
              <Input
                type="search"
                placeholder="Zoeken..."
                className="pl-10 w-48 bg-transparent border-primary/50 text-white placeholder:text-gray-400 focus:border-primary hover:border-primary/70 transition-colors"
              />
            </div>
            <Button variant="outline" className="border-primary/50 text-white hover:bg-primary/10 bg-transparent font-medium text-sm hover:scale-105 transition-all">
              INLOGGEN
            </Button>
            <Button className="bg-primary hover:bg-primary/90 text-black font-medium text-sm transition-all hover:scale-105">NIEUWSBRIEF</Button>
          </div>
        </div>

        {/* Mobile Navigation */}
        {isMenuOpen && (
          <div className="md:hidden bg-black/95 backdrop-blur-md border-t border-white/10 mt-4">
            <div className="px-6 py-4 space-y-4">
              <button onClick={navigateToHome} className="block w-full text-left text-white hover:text-primary transition-colors font-medium py-2 cursor-pointer">
                HOME
              </button>
              <button onClick={() => scrollToSection('events')} className="block w-full text-left text-white hover:text-primary transition-colors font-medium py-2 cursor-pointer">
                EVENTS
              </button>
              <button onClick={() => scrollToSection('videos')} className="block w-full text-left text-white hover:text-primary transition-colors font-medium py-2 cursor-pointer">
                VIDEO'S
              </button>
              <button onClick={() => scrollToSection('community')} className="block w-full text-left text-white hover:text-primary transition-colors font-medium py-2 cursor-pointer">
                COMMUNITY
              </button>
              <button onClick={() => scrollToSection('story')} className="block w-full text-left text-white hover:text-primary transition-colors font-medium py-2 cursor-pointer">
                STORY
              </button>
              <button onClick={() => scrollToSection('media')} className="block w-full text-left text-white hover:text-primary transition-colors font-medium py-2 cursor-pointer">
                MEDIA
              </button>
              <Link href="/tickets" className="block w-full text-left text-white hover:text-primary transition-colors font-medium py-2 cursor-pointer">
                TICKETS
              </Link>
              <div className="pt-4 border-t border-white/10">
                <Button className="w-full bg-primary hover:bg-primary/90 text-black font-medium text-sm transition-all cursor-pointer">
                  NIEUWSBRIEF
                </Button>
              </div>
            </div>
          </div>
        )}
      </div>
    </nav>
  )
}

// app/components/Navigation.vue
<template>
  <nav class="fixed top-0 left-0 right-0 z-50 bg-black/90 backdrop-blur-sm border-b border-white/10">
    <div class="container mx-auto px-6 py-4">
      <div class="flex items-center justify-between">
        <!-- Logo -->
        <NuxtLink to="/" class="flex items-center space-x-4 hover:opacity-80 transition-opacity">
          <NuxtImg 
            src="/logo/HakBorrel-LOGOS_white 1.png"
            alt="HakBorrel Logo"
            loading="eager"
            format="webp"
            quality="100"
            sizes="40px"
          />
          
          <span class="text-white font-display text-xl">HAKBORREL</span>
        </NuxtLink>

        <!-- Navigation Links -->
        <div class="hidden lg:flex items-center space-x-8">
          <NuxtLink to="/#home" class="text-gray-300 hover:text-white transition-colors font-body text-sm uppercase tracking-wide">
            HOME
          </NuxtLink>
          <NuxtLink to="/#events" class="text-gray-300 hover:text-white transition-colors font-body text-sm uppercase tracking-wide">
            EVENTS
          </NuxtLink>
          <NuxtLink to="/#agenda" class="text-gray-300 hover:text-white transition-colors font-body text-sm uppercase tracking-wide">
            AGENDA
          </NuxtLink>
          <NuxtLink to="/#videos" class="text-gray-300 hover:text-white transition-colors font-body text-sm uppercase tracking-wide">
            VIDEO'S
          </NuxtLink>
          <NuxtLink to="/#community" class="text-gray-300 hover:text-white transition-colors font-body text-sm uppercase tracking-wide">
            COMMUNITY
          </NuxtLink>
          <NuxtLink to="/#story" class="text-gray-300 hover:text-white transition-colors font-body text-sm uppercase tracking-wide">
            STORY
          </NuxtLink>
          <NuxtLink to="/#media" class="text-gray-300 hover:text-white transition-colors font-body text-sm uppercase tracking-wide">
            MEDIA
          </NuxtLink>
          <NuxtLink to="/tickets" class="text-gray-300 hover:text-white transition-colors font-body text-sm uppercase tracking-wide">
            TICKETS
          </NuxtLink>
        </div>

        <!-- Right Side Actions -->
        <div class="hidden lg:flex items-center space-x-4">
          <!-- Search Bar -->
          <div class="relative">
            <input 
              type="text" 
              placeholder="Zoeken..." 
              class="bg-black/50 border border-white/20 rounded-lg px-4 py-2 pr-10 text-white placeholder-gray-400 text-sm focus:outline-none focus:border-green-500/50 transition-colors"
            />
            <Icon name="heroicons:magnifying-glass" size="16px" class="absolute right-3 top-1/2 transform -translate-y-1/2 text-gray-400" />
          </div>
          
          <!-- Login Button -->
          <button class="bg-transparent border border-white/30 text-white px-4 py-2 rounded-lg text-sm font-medium hover:bg-white/10 transition-colors">
            INLOGGEN
          </button>
          
          <!-- Newsletter Button -->
          <button class="bg-green-500 text-white px-4 py-2 rounded-lg text-sm font-medium hover:bg-green-600 transition-colors">
            NIEUWSBRIEF
          </button>
        </div>

        <!-- Mobile Menu Button -->
        <button class="lg:hidden text-white transition-transform duration-300 hover:scale-110" @click="toggleMobileMenu">
          <Icon name="heroicons:bars-3" size="24px" v-if="!isMobileMenuOpen" />
          <Icon name="heroicons:x-mark" size="24px" v-else />
        </button>
      </div>

      <!-- Mobile Menu -->
      <Transition name="slide-down" appear>
        <div v-if="isMobileMenuOpen" class="lg:hidden mt-4 pb-4 border-t border-white/10 overflow-hidden">
          <div class="flex flex-col space-y-4 pt-4">
            <NuxtLink to="/#home" @click="closeMobileMenu" class="text-gray-300 hover:text-white transition-colors font-body text-sm uppercase tracking-wide py-2">
              HOME
            </NuxtLink>
            <NuxtLink to="/#events" @click="closeMobileMenu" class="text-gray-300 hover:text-white transition-colors font-body text-sm uppercase tracking-wide py-2">
              EVENTS
            </NuxtLink>
            <NuxtLink to="/#agenda" @click="closeMobileMenu" class="text-gray-300 hover:text-white transition-colors font-body text-sm uppercase tracking-wide py-2">
              AGENDA
            </NuxtLink>
            <NuxtLink to="/#videos" @click="closeMobileMenu" class="text-gray-300 hover:text-white transition-colors font-body text-sm uppercase tracking-wide py-2">
              VIDEO'S
            </NuxtLink>
            <NuxtLink to="/#community" @click="closeMobileMenu" class="text-gray-300 hover:text-white transition-colors font-body text-sm uppercase tracking-wide py-2">
              COMMUNITY
            </NuxtLink>
            <NuxtLink to="/#story" @click="closeMobileMenu" class="text-gray-300 hover:text-white transition-colors font-body text-sm uppercase tracking-wide py-2">
              STORY
            </NuxtLink>
            <NuxtLink to="/#media" @click="closeMobileMenu" class="text-gray-300 hover:text-white transition-colors font-body text-sm uppercase tracking-wide py-2">
              MEDIA
            </NuxtLink>
            <NuxtLink to="/tickets" @click="closeMobileMenu" class="text-gray-300 hover:text-white transition-colors font-body text-sm uppercase tracking-wide py-2">
              TICKETS
            </NuxtLink>
            
            <!-- Mobile Search -->
            <div class="relative mt-4">
              <input 
                type="text" 
                placeholder="Zoeken..." 
                class="w-full bg-black/50 border border-white/20 rounded-lg px-4 py-2 pr-10 text-white placeholder-gray-400 text-sm focus:outline-none focus:border-green-500/50 transition-colors"
              />
              <Icon name="heroicons:magnifying-glass" size="16px" class="absolute right-3 top-1/2 transform -translate-y-1/2 text-gray-400" />
            </div>
            
            <!-- Mobile Buttons -->
            <div class="flex space-x-2 mt-4">
              <button class="flex-1 bg-transparent border border-white/30 text-white px-4 py-2 rounded-lg text-sm font-medium hover:bg-white/10 transition-colors">
                INLOGGEN
              </button>
              <button class="flex-1 bg-green-500 text-white px-4 py-2 rounded-lg text-sm font-medium hover:bg-green-600 transition-colors">
                NIEUWSBRIEF
              </button>
            </div>
          </div>
        </div>
      </Transition>
    </div>
  </nav>
</template>

<script setup>
import { ref } from 'vue'

const isMobileMenuOpen = ref(false)

const toggleMobileMenu = () => {
  isMobileMenuOpen.value = !isMobileMenuOpen.value
}

const closeMobileMenu = () => {
  isMobileMenuOpen.value = false
}
</script>

<style scoped>
.slide-down-enter-active,
.slide-down-leave-active {
  transition: all 0.3s ease-in-out;
  max-height: 1000px;
}

.slide-down-enter-from,
.slide-down-leave-to {
  opacity: 0;
  max-height: 0;
}
</style>
