// components/video-section.tsx
"use client"

import { Play, ExternalLink, Calendar, Eye } from "lucide-react"
import { useState, useEffect } from "react"
import Link from "next/link"
import Image from "next/image"

// Single featured video - ready for YouTube API integration
const featuredVideo = {
  id: "featured",
  title: "HAKBORREL 2024 - OFFICIAL AFTERMOVIE",
  description: "Experience the raw energy and underground spirit of our latest gathering. Watch the highlights from our most intense event yet.",
  youtubeId: "SOH49z-S0G0", // Updated with actual YouTube video ID
  duration: "4:32",
  views: "28K",
  publishedAt: "2024-01-15",
  // YouTube thumbnail URL - automatically generated by YouTube
  thumbnail: "https://img.youtube.com/vi/SOH49z-S0G0/hqdefault.jpg"
}

export function VideoSection() {
  const [isHovered, setIsHovered] = useState(false)
  const [isVideoLoaded, setIsVideoLoaded] = useState(false)
  const [isClient, setIsClient] = useState(false)

  // Fix hydration issue by ensuring client-side rendering for date formatting
  useEffect(() => {
    setIsClient(true)
  }, [])

  const handleVideoClick = () => {
    if (!isVideoLoaded) {
      setIsVideoLoaded(true)
    } else {
      // Open in YouTube for better experience
      window.open(`https://www.youtube.com/watch?v=${featuredVideo.youtubeId}`, '_blank')
    }
  }

  // Format date safely for SSR
  const formatDate = (dateString: string) => {
    if (!isClient) return dateString // Return raw string during SSR
    return new Date(dateString).toLocaleDateString()
  }

  return (
    <section className="relative section-padding overflow-hidden">

      <div className="container-professional relative z-10 max-w-5xl">
        {/* Professional header */}
        <div className="text-center mb-20">
          <div className="inline-flex items-center gap-4 mb-8">
            <div className="w-1 h-12 bg-gradient-to-b from-primary to-primary/50"></div>
            <h2 className="text-5xl md:text-7xl font-display">
              <span className="text-white">FEATURED</span>{" "}
              <span className="text-gradient-primary">VIDEO</span>
            </h2>
            <div className="w-1 h-12 bg-gradient-to-b from-primary to-primary/50"></div>
          </div>
          <p className="text-gray-300 text-xl max-w-3xl mx-auto leading-relaxed font-body">
            Watch our latest aftermovie and experience the underground hardcore movement.
          </p>
        </div>

        {/* Professional video player */}
        <div className="max-w-4xl mx-auto">
          <div
            className="group relative aspect-video overflow-hidden rounded-xl border border-gray-700/50 hover:border-primary/50 transition-all duration-500 cursor-pointer bg-gray-900/50 backdrop-blur-smooth hover-lift"
            onMouseEnter={() => setIsHovered(true)}
            onMouseLeave={() => setIsHovered(false)}
            onClick={handleVideoClick}
          >
            {!isVideoLoaded ? (
              <>
                {/* YouTube thumbnail */}
                <Image
                  src="https://img.youtube.com/vi/SOH49z-S0G0/hqdefault.jpg"
                  alt={featuredVideo.title}
                  fill
                  className="object-cover transition-transform duration-700 group-hover:scale-105"
                />

                {/* Professional overlay */}
                <div className="absolute inset-0 bg-gradient-to-t from-black/80 via-black/20 to-transparent" />

                {/* Play button */}
                <div className="absolute inset-0 flex items-center justify-center">
                  <div
                    className={`w-20 h-20 rounded-full flex items-center justify-center transition-all duration-500 ${
                      isHovered ? "bg-primary scale-110 shadow-[0_0_40px_rgba(57,255,20,0.6)]" : "bg-primary/90 shadow-[0_0_20px_rgba(57,255,20,0.4)]"
                    }`}
                  >
                    <Play className="h-8 w-8 text-black fill-black ml-1" />
                  </div>
                </div>

                {/* Video info */}
                <div className="absolute bottom-0 left-0 right-0 p-6">
                  <h3 className="text-white font-bold text-xl md:text-2xl mb-2">{featuredVideo.title}</h3>
                  <p className="text-gray-300 text-sm md:text-base mb-3 line-clamp-2">{featuredVideo.description}</p>
                  <div className="flex items-center gap-4 text-sm text-gray-400">
                    <span className="flex items-center gap-1">
                      <Play className="h-3 w-3" />
                      {featuredVideo.duration}
                    </span>
                    <span>•</span>
                    <span className="flex items-center gap-1">
                      <Eye className="h-3 w-3" />
                      {featuredVideo.views} views
                    </span>
                    <span>•</span>
                    <span className="flex items-center gap-1" suppressHydrationWarning>
                      <Calendar className="h-3 w-3" />
                      {formatDate(featuredVideo.publishedAt)}
                    </span>
                  </div>
                </div>

                {/* Duration badge */}
                <div className="absolute top-4 right-4 bg-black/80 px-3 py-1 rounded-md text-white text-sm font-medium backdrop-blur-sm">
                  {featuredVideo.duration}
                </div>

                {/* YouTube branding */}
                <div className="absolute top-4 left-4 bg-red-600 px-3 py-1 rounded-md text-white text-xs font-bold flex items-center gap-1 backdrop-blur-sm">
                  <ExternalLink className="h-3 w-3" />
                  YouTube
                </div>
              </>
            ) : (
              /* Embedded YouTube video */
              <iframe
                width="100%"
                height="100%"
                src={`https://www.youtube.com/embed/${featuredVideo.youtubeId}?autoplay=1&rel=0`}
                title={featuredVideo.title}
                frameBorder="0"
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                allowFullScreen
                className="w-full h-full"
              />
            )}
          </div>

          {/* Professional action section */}
          <div className="mt-12 text-center">
            <p className="text-gray-400 text-base mb-8 font-body">
              More videos coming soon. Subscribe to our channel for the latest content.
            </p>
            <div className="flex justify-center gap-6">
              <Link href="/tickets">
                <button className="btn-professional px-8 py-3 cursor-pointer">
                  GET TICKETS
                </button>
              </Link>
              <button className="btn-professional btn-secondary px-8 py-3 cursor-pointer">
                SUBSCRIBE
              </button>
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}

// app/components/VideoSection.vue
<template>
  <!-- Video Section -->
  <div id="videos" class="relative section-padding overflow-hidden pb-16 bg-black/20">
    
    <!-- Background Effects -->
    <div class="absolute inset-0 opacity-5" 
         style="background-image: url('data:image/svg+xml,%3Csvg width=\'120\' height=\'120\' viewBox=\'0 0 120 120\' xmlns=\'http://www.w3.org/2000/svg\'%3E%3Cg fill=\'%23ffffff\' fill-opacity=\'0.01\'%3E%3Ccircle cx=\'30\' cy=\'30\' r=\'1\'/%3E%3Ccircle cx=\'90\' cy=\'30\' r=\'1\'/%3E%3Ccircle cx=\'30\' cy=\'90\' r=\'1\'/%3E%3Ccircle cx=\'90\' cy=\'90\' r=\'1\'/%3E%3Ccircle cx=\'60\' cy=\'60\' r=\'1\'/%3E%3C/g%3E%3C/svg%3E');" />

    <!-- Side glows -->
    <div class="absolute top-1/2 left-0 w-48 h-48 bg-purple-500/6 rounded-full blur-[80px] -translate-y-1/2 animate-smooth-flow" style="animation-duration: 20s;" />
    <div class="absolute top-1/2 right-0 w-48 h-48 bg-green-500/6 rounded-full blur-[80px] -translate-y-1/2 animate-smooth-flow" style="animation-duration: 25s; animation-delay: 5s;" />

    <div class="container mx-auto px-4 sm:px-6 relative z-10">
      <div class="text-center mb-12 sm:mb-16 lg:mb-20">
        <div class="inline-flex items-center gap-3 sm:gap-4 mb-6 sm:mb-8">
          <div class="w-1 h-8 sm:h-12 bg-gradient-to-b from-purple-500 to-purple-500/50"></div>
          <h2 class="text-3xl sm:text-4xl md:text-5xl lg:text-7xl font-display">
            <span class="text-white">FEATURED </span>
            <span class="text-gradient-secondary">VIDEO</span>
          </h2>
          <div class="w-1 h-8 sm:h-12 bg-gradient-to-b from-purple-500 to-purple-500/50"></div>
        </div>
        <p class="text-gray-300 text-base sm:text-lg lg:text-xl max-w-3xl mx-auto mb-8 sm:mb-12 leading-relaxed font-body">
          Experience the raw energy and underground vibes through our latest video content.
        </p>
      </div>

      <!-- Featured Video -->
      <div class="max-w-6xl mx-auto">
        <div class="relative bg-black/60 backdrop-blur-sm border border-purple-500/30 rounded-lg overflow-hidden hover:border-purple-500 transition-all duration-300 hover:shadow-[0_0_30px_rgba(147,51,234,0.3)]">
          
          <!-- YouTube Video Embed -->
          <div class="relative aspect-video w-full overflow-hidden rounded-lg">
            <iframe 
              :src="youtubeEmbedUrl"
              title="YouTube video player"
              frameborder="0"
              allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
              allowfullscreen
              class="absolute inset-0 w-full h-full"
              style="border: none;"
            ></iframe>
          </div>
        </div>
      </div>

    </div>
  </div>
</template>

<script setup>
// YouTube video URL
const youtubeUrl = 'https://www.youtube.com/watch?v=SOH49z-S0G0'

// Convert YouTube URL to embed URL
const youtubeEmbedUrl = computed(() => {
  const videoId = youtubeUrl.split('v=')[1]?.split('&')[0]
  return `https://www.youtube.com/embed/${videoId}?rel=0&modestbranding=1&showinfo=0&controls=1&fs=1&cc_load_policy=0&iv_load_policy=3&autohide=0`
})

// Video data
const featuredVideo = {
  id: "1",
  title: "UNDERGROUND RAVE #22 - AFTERMOVIE",
  description: "Experience the raw energy and underground vibes from our latest rave. Feel the bass, see the crowd, and get ready for the next one.",
  date: "2 weeks ago",
  location: "Secret Location, Amsterdam",
  genre: "Hardcore Techno"
}
</script>
